### ISSUE TITLE
When quadmath include dir is not found ...

### ISSUE THREAD

**Issue by darioizzo** [bluescarni/mppp#142]
When including mppp in my project, since the quadmath header is not found by cmake everything stops. I do have the header in the folder ```/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/include```
which is included by default when compiling using gcc. That directory is not searched by cmake find_path.

Looking at the file https://github.com/bluescarni/mppp/blob/master/cmake/FindQuadmath.cmake:
```
find_path(Quadmath_INCLUDE_DIR NAMES quadmath.h)
find_library(Quadmath_LIBRARY NAMES quadmath)

if(NOT Quadmath_INCLUDE_DIR OR NOT Quadmath_LIBRARY)
    cmake_push_check_state(RESET)
    list(APPEND CMAKE_REQUIRED_LIBRARIES "quadmath")
    CHECK_CXX_SOURCE_COMPILES("
        #include <quadmath.h>
        int main(void){
            __float128 foo = ::sqrtq(123.456);
        }"
    Quadmath_USE_DIRECTLY)
    cmake_pop_check_state()
    if (Quadmath_USE_DIRECTLY)
        set(Quadmath_INCLUDE_DIR "unused" CACHE PATH "" FORCE)
        set(Quadmath_LIBRARY "quadmath" CACHE FILEPATH "" FORCE)
    endif()
endif()

find_package_handle_standard_args(Quadmath DEFAULT_MSG Quadmath_LIBRARY Quadmath_INCLUDE_DIR)
```
In my archlinux system (gcc (GCC) 8.1.0) ```findpath ``` fails, so ```Quadmath_INCLUDE_DIR``` does not get defined.  Later ```CHECK_CXX_SOURCE_COMPILES``` also fails as libquadmath is not linked and sqrtq is not found. As a consequence ```find_package_handle_standard_args``` fails resulting in and error.

is it necessary to look for the include dir since quadmath.h is anyway in the system path of the compiler? Or is there a better way of setting this up?

**Comment by bluescarni** [comment]
The quadmath detection is a bit tricky, because ``quadmath.h`` and ``libquadmath.so`` may or may not be in standard paths (depending, e.g., on the linux distribution), but GCC is always able to pick them up regardless.

So that bit of CMake code you quoted first tries to locate ``quadmath.h`` and ``libquadmath.so`` in the standard paths, and, if it doesn't manage, it tries to compile a small quadmath test code by linking directly to ``-lquadmath``.

I just tried on my GCC 8 installation and it is still working as expected (as it does on the CI), so I am wondering if perhaps you can paste the exact CMake output so we can understand what is going on. Do you have some cached variables making a mess perhaps?

**Comment by bluescarni** [comment]
To elaborate further, the reason why we bother with actually trying to find ``quadmath.h`` and ``libquadmath.so`` is to support clang. Clang does support ``__float128`` natively, but in order to call the functions from the quadmath API you do need to have the full path to ``quadmath.h`` and ``libquadmath.so`` in order for the include and the linking to work.

**Comment by bluescarni** [comment]
Is this still an issue or can this be closed?

**Comment by darioizzo** [comment]
Not an issue for me anymore .... probably I messed up some cars ...
