### ISSUE TITLE
Version 0.15 installs libraries with mismatching version numbers

### ISSUE THREAD

**Issue by yurivict** [bluescarni/mppp#185]
```
lib/libmp++.so.1
lib/libmp++.so.0.15
```

```1``` and ```0``` above should be the same number.

**Comment by bluescarni** [comment]
@yurivict sorry I am confused. What should be the relation between those numbers?

My understanding was that ``lib/libmp++.so.0.15`` represents the mp++ library version, while the ``lib/libmp++.so.1`` symlink represents the ABI compatibility version. Because mp++ does not guarantee binary compatibility from version to version, the ABI number gets bumped up at each new library version.

Would you prefer to have a single ``lib/libmp++.so.0.15`` file?

**Comment by yurivict** [comment]
It should be for ex.
```
lib/libmp++.so.1
lib/libmp++.so.1.15
```

See some random examples from /usr/local/lib:
```
$ ls /usr/local/lib/
...
libchm.so                                  libinchi.so                                libsndio.so                                sasl2
libchm.so.0                                libinchi.so.0                              libsndio.so.6.1                            scons-3.0.1
libchm.so.0.0.0                            libinchi.so.0.4.1                          libsodium.a                                shared-modules
libcholmod.so                              libinotify.a                               libsodium.so                               siconv
libcholmod.so.3                            libinotify.so                              libsodium.so.23                            sigc++-2.0
libcholmod.so.3.0.12                       libinotify.so.0                            libsodium.so.23.1.0                        signon
unarx-2
...
```

The ```lib/libmp++.so.A``` link represents the SONAME that is written into ```lib/libmp++.so.A.B.C```

**Comment by bluescarni** [comment]
> It should be for ex.
> 
> ```
> lib/libmp++.so.1
> lib/libmp++.so.1.15
> ```

Can I use numbers here which are unrelated to the mp++ version number? E.g., for mp++-0.15, can I have

```
lib/libmp++.so.1
lib/libmp++.so.1.0
```

Then for mp++-0.16

```
lib/libmp++.so.2
lib/libmp++.so.2.0
```

and so on? Would that be acceptable?

**Comment by yurivict** [comment]
Yes.

**Comment by bluescarni** [comment]
Ok I'll implement it now.

**Comment by bluescarni** [comment]
PR up at #187. Thanks for reporting this.

**Comment by bluescarni** [comment]
Do you have any chance of testing out the latest master branch to see if now the versioning is correct?

**Comment by yurivict** [comment]
It looks good. Thanks for fixing this!

**Comment by bluescarni** [comment]
> It looks good. Thanks for fixing this!

No problem, thanks for reporting! I made a 0.16 release with this fix.

**Comment by bluescarni** [comment]
@yurivict I have a PR open which attempts to auto-detect the correct library installation path for ``libmp++.so`` in Unix systems. Previously, the path would always be ``${PREFIX}/lib``, but now it could be something like ``${PREFIX}/lib64`` or ``${PREFIX}/lib32``, depending on the architecture. This change is necessary because in some Linux multilib systems (e.g., amd64 systems which need to be able to run also 32-bit code) there are different installation paths for the libraries, depending on the architecture the library was compiled for. #193 is an attempt to cope with this kind of situation.

Is this ok as far as FreeBSD is concerned?
