### ISSUE TITLE
How to use uint256_t?

### ISSUE THREAD

**Issue by NicolasYL** [bluescarni/mppp#189]
I want to use a uint256_t variable ，just like this：
const uint256_t a("0xF4DF741DE58BCB2F37F18372026EF9CBCFC456CB80AF54D53BDEED78410065DE");
  const uint256_t b("1233423452345242346523426534652345235233245");

  const uint256_t c = (a * b);
  const uint256_t d = (a + b);
const uint256_t e =a++;
const uint256_t f = a__;
cout<<a.str();

Can you help me?thanks.

**Comment by NicolasYL** [comment]
Another quaetion is :
mp++ is header file only ? I want to add it to my project by including  headfile only,is accessible?

**Comment by bluescarni** [comment]
@NicolasYL mp++ is not header only: it always required linking to the GMP library, and, since a couple of versions, mp++ comes with a (small) compiled library component as well (previously, the mp++ source was header-only).

The mp++ integer class is not a fixed-size integer, it is an arbitrary-precision integer, meaning that its bit width changes automatically at runtime to accommodate any numerical value (as long as it fits in memory). If you are looking for a fixed-width 256bit integer class, probably you would be better served by the Boost.Multiprecision classes.

What you can do in mp++, is to configure the integer class to store up to 256 bits inline in the class without resorting to dynamic memory allocation, which can improve performance via better cache locality. E.g.,

```c++
#include <mp++/integer.hpp>

using int256_t = mppp::integer<4>; // Assuming a 64bit limb size, 64*4=256 bits.
```

Note that however an ``int256_t`` defined this way won't give you wrap-around behaviour.

**Comment by NicolasYL** [comment]
Thank you for reply!
