### ISSUE TITLE
libarb is has been rolled into libflint-arb.  CMakeFileList.txt needs to be updated.

### ISSUE THREAD

**Issue by Tafnab** [bluescarni/mppp#311]
I was just building your lib when I found out [libarb has been merged into Flint](https://github.com/fredrik-johansson/arb).  Debian 12 supplies libflint-arb2 and libflint-arb-dev packages.  They install arb.h and the rest of the old arb.

I couldn't figure out your cmake setup to change that.  It would depend on the version of flint >2.x. The new arb files seem to be installed pretty much where you would expect, however the cmake bombs when I try to build WITH_ARB.

Thanks.

**Comment by bluescarni** [comment]
Hi @Tafnab!

Yes it is a bit of a tricky situation. I am a bit unsure on how to proceed, given that for at least a while older versions of flint/arb (as separate packages) will still be around and will have to be supported. The fact that even in the new flint versions they are still using autotools on Unix instead of CMake does not help (with CMake it would be much easier to detect the version of flint for instance).

If you want to take a crack at updating mp++'s build system for the new flint, a PR would be much appreciated.

**Comment by Tafnab** [comment]
The reason I mentioned the new pacakge names is that, if they are present, it must be the new arb.  It will hopefully be easy to fix cmake by first testing for the new package and, if not present, failing over to the old.

However, I really don't like cmake.  Every time I have to fix some cmake build, it's with a manual and stackoverflow helping me. I'll eventually take a crack at it, but I'm currently fixing *other* packages.  Your CMakeLists.txt works very well with ccmake, but it looks complicated.

**Comment by 7ofNine** [comment]
I think an additional issue could be that flintlib has dropped mpir support with version 3.1.0. Which creates the fun of trying to compile gmp on windows. For 64 bits that might be an interesting challenge. I don't know if using cygwin for compilation would be enough. I.e. starting to use flintlib in connection with mppp on windows, which is so far no great problem, would practically kill mppp usage.

**Comment by bluescarni** [comment]
PR up now at #319.

**Comment by bluescarni** [comment]
#319 has been merged, closing.
